Update Operator SDK to 1.21.0
openshift/aws-efs-operator pull request #49
Opened 2022-09-14 02:23 UTC by johnxo-rh

Update operator-sdk to v1.21.0
https://issues.redhat.com/browse/OSD-12091

2022-09-14 03:44 UTC, wanghaoran1988 commented on build/Dockerfile
> +FROM golang:1.17 as builder
The boilerplate already have golang, you should remove this.

2022-09-15 14:22 UTC, 2uasimojo reviewed
I didn't go through this in depth, but I see a *lot* of changes I don't understand.

A lot of test cases/paths have been removed or commented out -- why is that?

Some new files were introduced that seem like they should be part of an import, like mapper.go, k8sutil.go, logger.go

Some files were deleted or replaced by stock versions, like the README and sample SharedVolume manifests (should the latter just have been moved instead?).

---

On a more general note, I don't know if we're even supporting this operator at all anymore. @jharrington22 @dustman9000 ?

2022-09-15 14:22 UTC, 2uasimojo commented on README.md
> -# AWS EFS Operator for OpenShift Dedicated
It looks like this README was replaced by a stock/generated one. Is there a reason the old content is no good?

2022-09-15 19:06 UTC, jharrington22 requested changes
I left some comments but similar concerns to @2uasimojo

2022-09-15 19:06 UTC, jharrington22 commented on README.md
> -# AWS EFS Operator for OpenShift Dedicated
Why is this README changing? I don't see the contents anywhere else?

2022-09-15 19:06 UTC, jharrington22 commented on pkg/util/ensurable_test.go
> +	crclient "sigs.k8s.io/controller-runtime/pkg/client"
The naming of this is confusing, `crclient` to me means CodeReady Containers (https://developers.redhat.com/products/openshift-local/overview)

2022-09-15 19:06 UTC, jharrington22 commented on pkg/util/predicate_test.go
> -		mktest(care, care, care, care, true),
Why are these test cases being removed?

2022-09-15 19:06 UTC, jharrington22 commented on pkg/util/predicate_test.go
> +// func mkTestMeta(kind testObjKind) metav1.Object {
Is this metadata not needed anymore?

2022-09-15 19:06 UTC, jharrington22 commented on controllers/statics/statics_test.go
>  func TestEnsureStaticsError(t *testing.T) {
Why are these tests removed?

2022-09-15 19:08 UTC, jharrington22 commented
> I didn't go through this in depth, but I see a _lot_ of changes I don't understand.
> 
> A lot of test cases/paths have been removed or commented out -- why is that?
> 
> Some new files were introduced that seem like they should be part of an import, like mapper.go, k8sutil.go, logger.go
> 
> Some files were deleted or replaced by stock versions, like the README and sample SharedVolume manifests (should the latter just have been moved instead?).
> 
> On a more general note, I don't know if we're even supporting this operator at all anymore. @jharrington22 @dustman9000 ?

We don't have a migration path from this to the new OCP supported operator so we're updating the SDK to keep it inline with our development environment so that if we need to do any maintenance it shouldn't be difficult. This will also allow us to update controller runtime deps etc.

2022-09-15 21:48 UTC, dustman9000 commented
/hold 
Currently aws-efs-operator is no longer supported by RH. There has been work done with [SDE-1759](https://issues.redhat.com/browse/SDE-1759) to close this gap and provide a migration path for customers to use the supported operator.

2022-09-16 02:45 UTC, johnxo-rh commented on README.md
> -# AWS EFS Operator for OpenShift Dedicated
I will update previous ReadMe and push

2022-09-16 02:46 UTC, johnxo-rh commented on pkg/util/ensurable_test.go
> +	crclient "sigs.k8s.io/controller-runtime/pkg/client"
This is the same naming standard followed in other operator upgrades. Eg: managed upgrade operator

2022-09-16 02:48 UTC, johnxo-rh commented on pkg/util/predicate_test.go
> +// func mkTestMeta(kind testObjKind) metav1.Object {
Yes

2022-09-16 02:49 UTC, johnxo-rh commented on controllers/statics/statics_test.go
>  func TestEnsureStaticsError(t *testing.T) {
Logger is not interface any more. Log.Expect () would not work.

2022-09-19 00:55 UTC, johnxo-rh commented on pkg/util/predicate_test.go
> -		mktest(care, care, care, care, true),
These are redundant test cases

2023-02-17 00:01 UTC, closed without merging